name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Replace .npmrc with the CI-ready version
        run: rm .npmrc && mv .npmrc.ci .npmrc
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@kwizapp'
      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: npm run lint:ci
      - run: npm run format:ci
      - run: npm test
        env:
          CI: 'true'
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          DATABASE_SSL: 'true'

  build_docker_hub:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build the Docker image
        run: docker build . --tag kwizapp/metadata-service:latest --build-arg NODE_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
      - name: Push the Docker image to Docker Hub
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master'
        run: docker push kwizapp/metadata-service

  build_heroku_stage:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/dev'

    steps:
      - uses: actions/checkout@v2
      - name: Pull the latest image from Docker Hub
        run: docker pull kwizapp/metadata-service:latest
      - uses: azure/docker-login@v1
        with:
          login-server: registry.heroku.com
          username: _
          password: ${{ secrets.HEROKU_API_KEY }}
      - name: Build the Docker image
        run: docker build . --cache-from kwizapp/metadata-service:latest --tag registry.heroku.com/kwiz-metadata-service-stage/web --build-arg NODE_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
      - name: Push the Docker image to Heroku
        run: docker push registry.heroku.com/kwiz-metadata-service-stage/web

  build_heroku:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      - name: Pull the latest image from Docker Hub
        run: docker pull kwizapp/metadata-service:latest
      - uses: azure/docker-login@v1
        with:
          login-server: registry.heroku.com
          username: _
          password: ${{ secrets.HEROKU_API_KEY }}
      - name: Build the Docker image
        run: docker build . --cache-from kwizapp/metadata-service:latest --tag registry.heroku.com/kwiz-metadata-service/web --build-arg NODE_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
      - name: Push the Docker image to Heroku
        run: docker push registry.heroku.com/kwiz-metadata-service/web

  deploy_stage:
    runs-on: ubuntu-latest
    needs: [test, build_heroku_stage]
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Login to Heroku
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:login
      - name: Release the new version
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:release -a kwiz-metadata-service-stage web

  deploy:
    runs-on: ubuntu-latest
    needs: [test, build_heroku]
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Login to Heroku
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:login
      - name: Release the new version
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:release -a kwiz-metadata-service web
